# Generated by Django 5.2.17 on 2026-09-03 05:19

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntityEnd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                (
                    "type",
                    django_enum.fields.EnumPositiveSmallIntegerField(
                        choices=[
                            (1, "Ended Early"),
                            (2, "Ended Normal"),
                            (4, "Elimated"),
                        ]
                    ),
                ),
                ("score", models.IntegerField()),
                ("ratings", models.JSONField(null=True)),
                ("video", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("site_id", models.SlugField()),
                ("tdf_name", models.CharField(max_length=100)),
                ("file_version", models.CharField(max_length=20)),
                ("software_version", models.CharField(max_length=20)),
                ("mission_type", models.PositiveSmallIntegerField()),
                ("mission_name", models.CharField(max_length=100)),
                ("ranked", models.BooleanField()),
                ("force_ended_early", models.BooleanField()),
                ("start_time", models.DateTimeField()),
                ("mission_duration", models.DurationField()),
                ("duration", models.DurationField()),
                ("penalty_amount", models.SmallIntegerField()),
                ("video", models.URLField(null=True)),
                ("team1_size", models.PositiveSmallIntegerField(null=True)),
                ("team2_size", models.PositiveSmallIntegerField(null=True)),
                ("log_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EntityStart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                ("entity_id", models.CharField(max_length=50)),
                (
                    "type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("player", "Player"),
                            ("standard-target", "Target"),
                            ("generator-target", "Generator Target"),
                            ("beacon", "Beacon"),
                            ("referee", "Referee"),
                        ],
                        max_length=16,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("level", models.SmallIntegerField()),
                (
                    "role",
                    django_enum.fields.EnumPositiveSmallIntegerField(
                        choices=[
                            (0, "Other"),
                            (1, "Commander"),
                            (2, "Heavy"),
                            (3, "Scout"),
                            (4, "Ammo"),
                            (5, "Medic"),
                        ]
                    ),
                ),
                ("battlesuit", models.CharField(max_length=50, null=True)),
                ("member_id", models.CharField(max_length=50, null=True)),
                (
                    "entity_end",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="laserforce_ranking.entityend",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_starts",
                        to="laserforce_ranking.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entityend",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="laserforce_ranking.entitystart",
            ),
        ),
        migrations.CreateModel(
            name="SM5Game",
            fields=[
                (
                    "game_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="laserforce_ranking.game",
                    ),
                ),
                ("rank_version", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "SM5 game",
                "verbose_name_plural": "SM5 games",
            },
            bases=("laserforce_ranking.game",),
        ),
        migrations.AddField(
            model_name="entityend",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entity_ends",
                to="laserforce_ranking.game",
            ),
        ),
        migrations.CreateModel(
            name="LaserballStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goals", models.PositiveSmallIntegerField()),
                ("assists", models.PositiveSmallIntegerField()),
                ("passes", models.PositiveSmallIntegerField()),
                ("steals", models.PositiveSmallIntegerField()),
                ("clears", models.PositiveSmallIntegerField()),
                ("blocks", models.PositiveSmallIntegerField()),
                ("shots_fired", models.PositiveSmallIntegerField()),
                ("shots_hit", models.PositiveSmallIntegerField()),
                ("started_with_ball", models.PositiveSmallIntegerField()),
                ("times_stolen", models.PositiveSmallIntegerField()),
                ("times_blocked", models.PositiveSmallIntegerField()),
                ("passes_received", models.PositiveSmallIntegerField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laserforce_ranking.entitystart",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laserball_stats",
                        to="laserforce_ranking.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laserball stat",
                "verbose_name_plural": "Laserball stats",
            },
        ),
        migrations.AddField(
            model_name="entitystart",
            name="laserball_stats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="laserforce_ranking.laserballstats",
            ),
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_id", models.CharField(max_length=15, unique=True)),
                ("codename", models.CharField(max_length=50)),
                ("player_id", models.SlugField(null=True, unique=True)),
                ("ratings", models.JSONField(default=dict)),
                ("home_site", models.SlugField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("password", models.CharField(max_length=255, null=True)),
                (
                    "permissions",
                    django_enum.fields.EnumPositiveSmallIntegerField(
                        choices=[(0, "User"), (1, "Admin")], default=0
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("permissions__in", [0, 1])),
                        name="laserforce_ranking_Player_permissions_Permission",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                (
                    "state",
                    django_enum.fields.EnumPositiveSmallIntegerField(
                        choices=[
                            (0, "Active"),
                            (1, "Unknown"),
                            (2, "Resettable"),
                            (3, "Down"),
                        ]
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laserforce_ranking.entitystart",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_states",
                        to="laserforce_ranking.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                ("old", models.IntegerField()),
                ("delta", models.SmallIntegerField()),
                ("new", models.IntegerField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laserforce_ranking.entitystart",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="laserforce_ranking.game",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SM5Stats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shots_hit", models.PositiveSmallIntegerField()),
                ("shots_fired", models.PositiveSmallIntegerField()),
                ("times_zapped", models.PositiveSmallIntegerField()),
                ("times_missiled", models.PositiveSmallIntegerField()),
                ("missile_hits", models.PositiveSmallIntegerField()),
                ("nukes_detonated", models.PositiveSmallIntegerField()),
                ("nukes_activated", models.PositiveSmallIntegerField()),
                ("nuke_cancels", models.PositiveSmallIntegerField()),
                ("medic_hits", models.PositiveSmallIntegerField()),
                ("own_medic_hits", models.PositiveSmallIntegerField()),
                ("medic_nukes", models.PositiveSmallIntegerField()),
                ("scout_rapid_fires", models.PositiveSmallIntegerField()),
                ("life_boosts", models.PositiveSmallIntegerField()),
                ("ammo_boosts", models.PositiveSmallIntegerField()),
                ("lives_left", models.PositiveSmallIntegerField()),
                ("shots_left", models.PositiveSmallIntegerField()),
                ("penalties", models.PositiveSmallIntegerField()),
                ("shot_3_hits", models.PositiveSmallIntegerField()),
                ("own_nuke_cancels", models.PositiveSmallIntegerField()),
                ("shot_opponent", models.PositiveSmallIntegerField()),
                ("shot_team", models.PositiveSmallIntegerField()),
                ("missiled_opponent", models.PositiveSmallIntegerField()),
                ("missiled_team", models.PositiveSmallIntegerField()),
                ("special_points", models.PositiveSmallIntegerField(null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laserforce_ranking.entitystart",
                    ),
                ),
                (
                    "entity_end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laserforce_ranking.entityend",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sm5_stats",
                        to="laserforce_ranking.sm5game",
                    ),
                ),
            ],
            options={
                "verbose_name": "SM5 stat",
                "verbose_name_plural": "SM5 stats",
            },
        ),
        migrations.AddField(
            model_name="entitystart",
            name="sm5_stats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="laserforce_ranking.sm5stats",
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("name", models.CharField(verbose_name=50)),
                ("color_enum", models.PositiveSmallIntegerField()),
                ("color_name", models.CharField(verbose_name=50)),
                ("real_color_name", models.CharField(verbose_name=50)),
                ("doubles_percent", models.FloatField(null=True)),
                ("score", models.IntegerField()),
                (
                    "entity_starts",
                    models.ManyToManyField(
                        related_name="teams", to="laserforce_ranking.entitystart"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="laserforce_ranking.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="winner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_games",
                to="laserforce_ranking.team",
            ),
        ),
        migrations.AddField(
            model_name="entitystart",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="laserforce_ranking.team",
            ),
        ),
        migrations.AddField(
            model_name="sm5game",
            name="last_team_standing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_team_standing",
                to="laserforce_ranking.team",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                (
                    "type",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("0100", "Mission Start"),
                            ("0101", "Mission End"),
                            ("0200", "Shot Empty"),
                            ("0201", "Miss"),
                            ("0202", "Miss Base"),
                            ("0203", "Hit Base"),
                            ("0204", "Destroy Base"),
                            ("0205", "Damaged Opponent"),
                            ("0206", "Downed Opponent"),
                            ("0207", "Damanged Team"),
                            ("0208", "Downed Team"),
                            ("0300", "Locking"),
                            ("0301", "Missile Base Miss"),
                            ("0302", "Missile Base Damage"),
                            ("0303", "Missile Base Destroy"),
                            ("0304", "Missile Miss"),
                            ("0305", "Missile Damage Opponent"),
                            ("0306", "Missile Down Opponent"),
                            ("0307", "Missile Damage Team"),
                            ("0308", "Missile Down Team"),
                            ("0400", "Activate Rapid Fire"),
                            ("0401", "Deactivate Rapid Fire"),
                            ("0404", "Activate Nuke"),
                            ("0405", "Detonate Nuke"),
                            ("0500", "Resupply Ammo"),
                            ("0502", "Resupply Lives"),
                            ("0510", "Ammo Boost"),
                            ("0512", "Life Boost"),
                            ("0600", "Penalty"),
                            ("0900", "Achievement"),
                            ("0902", "Reward"),
                            ("0B03", "Base Awarded"),
                            ("1100", "Pass"),
                            ("1101", "Goal"),
                            ("1102", "Assist"),
                            ("1103", "Steal"),
                            ("1104", "Block"),
                            ("1105", "Round Start"),
                            ("1106", "Round End"),
                            ("1107", "Gets Ball"),
                            ("1108", "Time Violation"),
                            ("1109", "Clear"),
                            ("110A", "Fail Clear"),
                            ("110B", "Reset On Base"),
                        ],
                        max_length=4,
                    ),
                ),
                ("entity1", models.CharField(default="", verbose_name=50)),
                ("action", models.CharField(default="", verbose_name=50)),
                ("entity2", models.CharField(default="", verbose_name=50)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="laserforce_ranking.game",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "type__in",
                                [
                                    "0100",
                                    "0101",
                                    "0200",
                                    "0201",
                                    "0202",
                                    "0203",
                                    "0204",
                                    "0205",
                                    "0206",
                                    "0207",
                                    "0208",
                                    "0300",
                                    "0301",
                                    "0302",
                                    "0303",
                                    "0304",
                                    "0305",
                                    "0306",
                                    "0307",
                                    "0308",
                                    "0400",
                                    "0401",
                                    "0404",
                                    "0405",
                                    "0500",
                                    "0502",
                                    "0510",
                                    "0512",
                                    "0600",
                                    "0900",
                                    "0902",
                                    "0B03",
                                    "1100",
                                    "1101",
                                    "1102",
                                    "1103",
                                    "1104",
                                    "1105",
                                    "1106",
                                    "1107",
                                    "1108",
                                    "1109",
                                    "110A",
                                    "110B",
                                ],
                            )
                        ),
                        name="laserforce_ranking_Event_type_EventType",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="entityend",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", [1, 2, 4])),
                name="laserforce_ranking_EntityEnd_type_EntityEndType",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerstate",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", [0, 1, 2, 3])),
                name="laserforce_ranking_PlayerState_state_PlayerStateType",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitystart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "player",
                            "standard-target",
                            "generator-target",
                            "beacon",
                            "referee",
                        ],
                    )
                ),
                name="laserforce_ranking_EntityStart_type_EntityType",
            ),
        ),
        migrations.AddConstraint(
            model_name="entitystart",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", [0, 1, 2, 3, 4, 5])),
                name="laserforce_ranking_EntityStart_role_IntRole",
            ),
        ),
    ]
