# Generated by Django 5.2.17 on 2026-09-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "laserforce_ranking",
            "0004_remove_entityend_laserforce_ranking_entityend_type_entityendtype_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="previous_codenames",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="team",
            name="is_neutral",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
