# Generated by Django 5.2.17 on 2026-09-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laserforce_ranking", "0005_player_previous_codenames_team_is_neutral"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="home_site",
            new_name="home_site_id",
        ),
    ]
